#pragma once

// Name: Fortnite, Version: OT-6_5


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function HuskVimBlueprint.HuskVimBlueprint_C.InitializeHuskType
struct UHuskVimBlueprint_C_InitializeHuskType_Params
{
	class AFortAIPawn*                                 InputPin;                                                  // (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_3E1AAF314A92EA9BAEBDFFA18BFDBE31
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_3E1AAF314A92EA9BAEBDFFA18BFDBE31_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_36293C764E66652AB51D6EA325B93C28
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_36293C764E66652AB51D6EA325B93C28_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_6881341D4EA79B64C4616A9783F931DB
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_6881341D4EA79B64C4616A9783F931DB_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_48E307964801AB51DD890898CBE35141
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_48E307964801AB51DD890898CBE35141_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_80B4C97B4CAC1F2C5D6A56957A7E29B2
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_80B4C97B4CAC1F2C5D6A56957A7E29B2_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_7A2A0F6849392A2F649C4FBB52941E96
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_7A2A0F6849392A2F649C4FBB52941E96_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_73BB9CA046F3F05341252D9489D72103
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_73BB9CA046F3F05341252D9489D72103_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_37EC6B6E4386A12C6F664688A4D188F4
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_37EC6B6E4386A12C6F664688A4D188F4_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_313802304B999C3D178C48BF9DEDEFAE
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_TransitionResult_313802304B999C3D178C48BF9DEDEFAE_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_440B1F274BAB6915F4A535B80FCB01C7
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_440B1F274BAB6915F4A535B80FCB01C7_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_88EDA46E4106E0FB2B6A9CAAE2C22DF3
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_88EDA46E4106E0FB2B6A9CAAE2C22DF3_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_CDBDFCB3423B7A666B668C810913101D
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_CDBDFCB3423B7A666B668C810913101D_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_97D40CFD4EB5645835403BA4924C0B3E
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_97D40CFD4EB5645835403BA4924C0B3E_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_61AAFD374F572C1FAC206E9A92B61F32
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_61AAFD374F572C1FAC206E9A92B61F32_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_9BEE9F054AD8E45DBB891E95496CC23A
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_9BEE9F054AD8E45DBB891E95496CC23A_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_43BBC9914EAAAC8C994CC4BA6D138971
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_43BBC9914EAAAC8C994CC4BA6D138971_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_A55CC7A2408CDC13BE5E2E909CDB724C
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_A55CC7A2408CDC13BE5E2E909CDB724C_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_D8B987814BC8214113BE1B9E22F44394
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_D8B987814BC8214113BE1B9E22F44394_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_89DB18E44181E92E530A8EB1C2835065
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_89DB18E44181E92E530A8EB1C2835065_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_487F72FF4CB1C079BB7DB69F6BB3314A
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_487F72FF4CB1C079BB7DB69F6BB3314A_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_BlendListByInt_73DCE67A4812F862ED8C6780A4006486
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_BlendListByInt_73DCE67A4812F862ED8C6780A4006486_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_6735E8134ECB24DD734FB68A0094224B
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_ModifyBone_6735E8134ECB24DD734FB68A0094224B_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_BlendListByBool_109F76DF4F31F5F29DEB3C9FAF5D09A5
struct UHuskVimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskVimBlueprint_AnimGraphNode_BlendListByBool_109F76DF4F31F5F29DEB3C9FAF5D09A5_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.AnimNotify_StunnedLeftState
struct UHuskVimBlueprint_C_AnimNotify_StunnedLeftState_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.AnimNotify_StunnedFullyBlendedState
struct UHuskVimBlueprint_C_AnimNotify_StunnedFullyBlendedState_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.AnimNotify_SleepingFullyBlended
struct UHuskVimBlueprint_C_AnimNotify_SleepingFullyBlended_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.AnimNotify_BeehiveDestroyed
struct UHuskVimBlueprint_C_AnimNotify_BeehiveDestroyed_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.BlueprintInitializeAnimation
struct UHuskVimBlueprint_C_BlueprintInitializeAnimation_Params
{
};

// Function HuskVimBlueprint.HuskVimBlueprint_C.ExecuteUbergraph_HuskVimBlueprint
struct UHuskVimBlueprint_C_ExecuteUbergraph_HuskVimBlueprint_Params
{
	int                                                EntryPoint;                                                // (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
